language: elixir
elixir:
  - 1.8
  - 1.7
  - 1.6
notifications:
  recipients:
    - brwcodes@gmail.com
    - ben.wilson@cargosense.com
otp_release:
  - 20.0
  - 21.0
script:
  - mix format --dry-run --check-formatted
  - mix test
